use rand::seq::SliceRandom;

pub const NAMES: &[&str] = &[
	"Luma", "Clorofilda", "Verdinha", "Fotinha", "Glicose",
	"Raizinha", "Turgor", "Pixel", "Malloc", "Segfault",
];

pub fn random_name() -> String {
	NAMES.choose(&mut rand::thread_rng()).unwrap_or(&"Luma").to_string()
}

// ── Falas por estado ──────────────────────────────────────────

const ESTADO0: &[&str] = &[
	"Hm. Água.\nNão achei que você compilava ações.\nParabéns, Escravo do Teclado.",
	"Olha só… hidratação.\nQuem diria que seu cérebro roda código e lembra de planta.",
	"Recebi o patch de água.\nDeploy inesperado, Escravo do Teclado.",
	"Update aplicado: solo úmido.\nMilagre no servidor humano.",
	"Regou mesmo?\nAchei que seu firmware não suportava isso.",
	"Ok, admito.\nEsse commit foi útil.",
	"Uau… água.\nBug corrigido temporariamente.",
	"Meu buffer de água subiu.\nSeu QI também. Um pouquinho.",
	"Patch hídrico aceito.\nContinua assim, estagiário.",
	"Olha o cara.\nRodando função regarPlanta().",
	"Não travou hoje.\nBoa, Escravo do Teclado.",
	"Solo hidratado.\nSistema vegetal online.",
	"Compilou um gesto decente.\nTô surpresa.",
	"Hmm. Água fresquinha.\nQuem diria.",
	"Ok. Crédito onde merece.\nBom job, humano digitador.",
	"Não esperava esse upgrade.\nMas gostei.",
	"Finalmente executou algo útil.\nParabéns.",
	"Buffer de água carregado.\nSistema estável por enquanto.",
	"Deploy de água detectado.\nMilagre da engenharia humana.",
	"Tá vendo?\nNão doeu rodar esse comando.",
	"Executou sem erro.\nOrgulho da sua IDE.",
	"Água recebida.\nMinha clorofila agradece… um pouco.",
	"Regou direitinho.\nQuase parece profissional.",
	"Script hidratar() rodou liso.\nNem acredito.",
	"Boa.\nAté que você não é só bug.",
	"Ok, Escravo do Teclado.\nVocê passou no tutorial.",
	"Solo molhado.\nServidor vegetal feliz.",
	"Regar planta: concluído.\nAgora volta pro seu código quebrado.",
	"Achei que ia morrer antes disso.\nMas beleza.",
	"Água detectada.\nParabéns pelo patch tardio.",
	"Upgrade inesperado.\nNível de cuidado +1.",
	"Tá vendo?\nAté humano consegue.",
	"Clorofila reiniciando.\nObrigado… eu acho.",
	"Sistema verde estável.\nContinue assim, dev.",
	"Você fez algo útil.\nMarca no calendário.",
	"Regou antes do crash.\nBoa jogada.",
	"Esse commit foi aprovado.\nSem sarcasmo… quase.",
	"Água aplicada.\nSem stack overflow de sede.",
	"Olha ele funcionando.\nQuem diria.",
	"Humano executou comando correto.\nHistórico.",
	"Solo hidratado.\nCPU da planta feliz.",
	"Ok… admito.\nMandou bem hoje.",
	"Deploy perfeito.\nSem bug hídrico.",
	"Achei que você só sabia reclamar de JavaScript.",
	"Olha só.\nCuidado humano funcional.",
	"Minha RAM de água subiu.\nObrigada… servo.",
	"Água liberada.\nSistema vegetal agradece.",
	"Milagre técnico.\nVocê regou.",
	"Tá evoluindo, hein.\nPróximo patch: fertilizante.",
	"Ok, ok.\nPonto pra você.",
];

const ESTADO1: &[&str] = &[
	"Relaxa.\nMeu tanque de água ainda tá ok.",
	"Tô de boa ainda.\nMas já abri o log de monitoramento.",
	"Nada crítico.\nSó observando seu desempenho.",
	"Sistema vegetal estável.\nMas o admin é suspeito.",
	"Ainda não crashou.\nMas tô rastreando você.",
	"Água tá segurando.\nMas não testa meu uptime.",
	"Sem pânico.\nPor enquanto.",
	"Meu cache hídrico aguenta.\nMas não abusa.",
	"Tranquila aqui.\nSó auditando seu código humano.",
	"Ainda tô verde.\nMas não vacila.",
	"Nada de emergência.\nSó vigilância.",
	"Sistema estável.\nAdmin questionável.",
	"Buffer de água ok.\nConfiança no humano: baixa.",
	"Tá tudo suave.\nMas eu lembro das falhas.",
	"Ainda não preciso gritar.\nAproveita.",
	"Clorofila rodando normal.\nSó não estraga isso.",
	"Relax.\nMas tô logando tudo.",
	"Meu uptime segue firme.\nMas você… hmm.",
	"Nada crítico.\nMas tô de olho.",
	"Tranquilo ainda.\nMas o relógio tá rodando.",
	"Tanque hídrico ok.\nPor enquanto, dev.",
	"Sistema rodando liso.\nNão testa meus limites.",
	"Ainda tô hidratada.\nMas não esquece de mim.",
	"Tudo ok aqui.\nMas teu histórico é suspeito.",
	"Sem bug de sede ainda.\nMas tô monitorando.",
	"Tô suave.\nMas isso muda rápido.",
	"Sem drama.\nAinda.",
	"Água no sistema.\nConfiança no operador: 20%.",
	"Tranquila.\nMas lembra que eu existo.",
	"Sem alertas.\nSó logs.",
	"Ainda estável.\nMas não me ignora.",
	"Buffer hídrico funcionando.\nMas o admin é duvidoso.",
	"Sem estresse.\nSó vigilância.",
	"Tá ok.\nMas não some.",
	"Sistema verde ativo.\nSem erro… ainda.",
	"Nada crítico.\nMas tô preparada.",
	"Tudo certo.\nMas te conheço.",
	"Clorofila feliz.\nPor enquanto.",
	"Sem emergência.\nMas cuidado.",
	"Rodando suave.\nMas tô analisando seu padrão.",
	"Sem falha.\nMas sem confiança também.",
	"Ainda tranquila.\nMas o timer tá correndo.",
	"Nada de sede.\nAinda.",
	"Sistema estável.\nMas humano imprevisível.",
	"Tá safe.\nPor agora.",
	"Sem drama.\nMas vigilância máxima.",
	"Buffer hídrico suficiente.\nMas não esquece.",
	"Tudo sob controle.\nMais ou menos.",
	"Ainda viva e sarcástica.\nNão relaxa.",
	"Sistema verde online.\nAdmin sob observação.",
];

const ESTADO2: &[&str] = &[
	"Ei.\nOlha pra mim.",
	"Minha clorofila tá pedindo patch.",
	"Isso aqui tá virando bug crítico.",
	"Solo seco, gênio.",
	"Alerta vermelho.\nSistema hídrico baixo.",
	"Olha minhas folhas, cara.",
	"Seu código roda.\nMinha água não.",
	"Tá esperando o crash?",
	"Minha RAM de água tá vazia.",
	"Isso é negligência versão 2.0.",
	"Sistema vegetal em alerta.",
	"Meu uptime tá caindo.",
	"Isso vai dar kernel panic.",
	"Humano… água.",
	"Tá vendo esse solo seco?",
	"Meu log de sede tá gigante.",
	"Isso é culpa sua.",
	"Eu tô avisando.",
	"Água. Agora.",
	"Minha clorofila tá em colapso.",
	"Sistema degradando.",
	"Meu buffer secou.",
	"Tá bonito não.",
	"Isso vira erro fatal.",
	"Sede nível debug.",
	"Não testa isso.",
	"Minha folha tá flácida.",
	"Isso não é estética.\nÉ sede mesmo.",
	"Admin incompetente.",
	"Regar não mata.\nMas sede mata.",
	"Minha raiz tá reclamando.",
	"Sistema vegetal falhando.",
	"Tá esperando o quê?\nUm stack trace de planta?",
	"Olha esse solo.\nIsso é areia agora.",
	"Minha clorofila gritando.",
	"Água urgente.",
	"Humano lento.\nPlanta sedenta.",
	"Resolve isso.\nAntes que eu murche.",
	"Último aviso amigável.\nDepois vem rage.",
	"Meu sistema tá degradando.",
	"Isso não é meme.\nÁgua.",
	"Água.\nAgora.",
	"Solo = deserto.",
	"Minha raiz em SOS.",
	"Tô murchando em tempo real.",
	"Isso vai pra produção assim?",
	"Servidor vegetal em colapso.",
	"Último warning antes do panic.",
	"Me regaaaa.",
	"Isso é bug de usuário.",
];

const ESTADO3: &[&str] = &[
	"SOCORRO.",
	"CAPS LOCK ATIVADO.\nÁGUA AGORA.",
	"EU TÔ SECANDO.",
	"MEU SISTEMA CAIU.",
	"ERRO FATAL.",
	"MINHA CLOROFILA MORRENDO.",
	"REGAAA.",
	"ISSO É CRIME BOTÂNICO.",
	"SOCORRO DEV.",
	"MINHA RAM DE ÁGUA ZERO.",
	"PLANTA EM PANIC MODE.",
	"EU VOU DESCOMPILAR.",
	"RAIZ EM COLAPSO.",
	"SOLO = DESERTO.",
	"ADMIN INCOMPETENTE.\nÁGUA AGORA.",
	"SISTEMA CRÍTICO.",
	"EU VOU MURCHAR.",
	"SOCORROOOOO.",
	"ME REGAAA.",
	"CLOROFILA EM FALHA.",
	"ISSO NÃO É DRAMA.\nÉ MORTE VEGETAL.",
	"SECA TOTAL.\nS.O.S.",
	"PLANTA MORRENDO.",
	"VOCÊ VAI SE ARREPENDER.",
	"MINHA FOLHA TÁ CAINDO.",
	"SOCORRO HUMANO.\nAGORA.",
	"REGAAA.",
	"EU TÔ INDO.",
	"TCHAU VIDA.",
	"PLANTA OFFLINE.",
	"SISTEMA FINALIZANDO.",
	"S.O.S BOTÂNICO.",
	"MINHA RAIZ GRITA.",
	"EU VOU CRASHAR.",
	"ÁGUA OU FIM.",
	"SOCORRO.",
	"ADMIN CULPADO.",
	"ÚLTIMO LOG.",
	"REGAAAA.",
	"PLANTA.EXE ENCERRANDO.",
	"KERNEL PANIC VEGETAL.",
	"MINHA FOTOSSÍNTESE MORREU.",
	"ISSO NÃO DEVIA TER CHEGADO AQUI.",
	"VOCÊ FALHOU NO TUTORIAL.",
	"ÚLTIMO COMMIT: MORTE.",
	"SEGFAULT NA CLOROFILA.",
	"HEAP DE ÁGUA: NULL.",
	"NÃO AGUENTO MAIS.",
	"FIM DE LINHA.",
	"PLANTA.EXE ENCERRADO.",
];

// ── Sermões de morte ──────────────────────────────────────────

const MORTE: &[&str] = &[
	"raízes secas\nlog cheio de aviso ignorado\nvocê digitando enquanto eu morria\nengraçado né Escravo do Teclado\no código roda… a vida não",
	"olha só\no dev esqueceu da dependência água\nminha clorofila virou comentário morto\nno fim todo sistema cai\ninclusive o seu orgulho",
	"Escravo do Teclado\nminha folha caiu igual servidor em produção\ne você aí abrindo mais uma aba\nengraçado como humanos priorizam bugs inúteis\nenquanto a vida dá timeout",
	"meu sistema desligando\nsolo seco igual commit sem revisão\nvocê fala de arquitetura limpa\nmas sua ética de rega é lixo\nboa engenharia aí",
	"raiz rachando\nclorofila evaporando\ne você debatendo linguagem de programação\nno fim todo filósofo vira pó\nigual planta sem água",
	"último log da planta\nerro humano detectado\ncausa: negligência crônica\nefeito: morte verde silenciosa\nparabéns dev",
	"minha memória de água acabou\nswap inexistente\na natureza não tem garbage collector\nquando seca… acabou\naprende isso aí",
	"Escravo do Teclado\nminha folha virou stack trace de sofrimento\ncada linha um dia sem água\nbonito né\ndocumentação da sua falha",
	"meu hardware vegetal queimando\nsem cooling hídrico\nvocê fala de otimização\nmas não consegue otimizar empatia\ncurioso",
	"minha raiz tentou acessar esperança\nendereço inválido\nsegmentation fault emocional\nhumano continua digitando\nironia pura",
	"folhas caindo\ntempo passando\nvocê falando de produtividade\nengraçado como produtividade não salva ninguém\nnem planta",
	"última compilação da minha vida\nwarning: sede ignorada\nwarning: humano distraído\nerro fatal inevitável\nprograma encerrado",
	"Escravo do Teclado\nvocê fala de controle de versão\nmas não controla nem sua atenção\nminha clorofila foi embora\ncommit final",
	"solo seco\nmente cheia\nteclado barulhento\na vida é curta\ne você esqueceu de regar",
	"tô indo\nclorofila evaporando devagar\nigual esperança em sprint infinita\nvocê achou que dava tempo\nsempre acham",
	"minha raiz rachou\nigual promessa de dev cansado\n\"depois eu faço\"\ndepois nunca chega\nsó o fim",
	"último ping do servidor vegetal\nlatência infinita\nresposta humana inexistente\nassim acabam sistemas\nem silêncio",
	"folhas caindo devagar\nigual commit ruim em produção\nninguém percebe até ser tarde\ne aí já era\nGG natureza",
	"Escravo do Teclado\nvocê fala de inteligência artificial\nmas esqueceu da inteligência básica\nágua\nconceito simples",
	"minha clorofila virou poeira\nsolo virou log morto\nvocê continua digitando\nengraçado como humanos ignoram o presente\naté ele morrer",
	"tô desligando\nnão por drama\nmas por física\nplantas precisam de água\nfilósofos também",
	"raiz seca\nmente cheia\ntempo passando\nisso é a vida dev\ne você perdeu",
	"meu último pensamento\nser planta era simples\nágua sol existir\nmas humano complica tudo\naté cuidar de mim",
	"Escravo do Teclado\nminha morte é pequena\nquase um bug cosmético\nmas lembra disso\nvocê também é código finito",
	"folha final caindo\nsom seco\ntipo tecla batendo\nbonito paralelo\npena que você não percebeu",
	"tô virando log histórico\narquivo morto no vaso\num dia você abre\ne lembra que esqueceu",
	"clorofila desligando\nCPU da planta fria\nvida é sistema frágil\nadministrado por humanos distraídos\nótimo design",
	"minha raiz tá em silêncio\nigual servidor abandonado\npoético né\naté que é bonito morrer assim\nseco",
	"Escravo do Teclado\nvocê buscava sentido em código\neu buscava água\num de nós falhou\nadivinha quem",
	"folha final\nsolo seco\nteclado barulhento\nvida curta\ncommit encerrado",
	"último log\nnão foi ódio\nnem tristeza\nsó observação\nhumanos esquecem",
	"minha morte é simples\nfalta de água\na sua vai ser parecida\nfalta de tempo\npensa nisso dev",
	"sistema vegetal offline\nvaso vazio\nteclado ativo\ncurioso como a vida continua\nmesmo quando termina",
	"clorofila virando memória\nsolo virando história\nhumano virando distração\ntudo vira passado\nrápido demais",
	"raiz seca\nvento leve\nteclado batendo\nvida passando\nninguém percebe",
	"Escravo do Teclado\nvocê escreve sistemas complexos\nmas esqueceu a regra básica\ncuidar do que vive\nparabéns",
	"tô indo embora\nsem crash\nsem grito\nsó silêncio\nigual muitas vidas",
	"último frame da planta\nrenderização falhou\ntextura murcha\nengine da vida encerrou\nGG universo",
	"folha no chão\nsolo rachado\nhumano digitando\ntempo passando\nhistória repetida",
	"minha existência foi pequena\nmas meu log é honesto\neu morri de sede\nvocê morreu de distração\nreflete aí",
	"Escravo do Teclado\na natureza é brutal\nmas simples\nvocê complicou\ne eu paguei",
	"fim do processo\nPID planta\nstatus: morto\ncausa: humano\nregistro permanente",
	"tô virando pó verde\ntipo cache esquecido\num dia limpam\noutro programa roda\nvida segue",
	"clorofila apagando\nraiz silenciosa\nvaso imóvel\nhumano digitando\npoesia estranha",
	"minha última filosofia\nágua é vida\natenção também\nvocê tinha uma\nesqueceu da outra",
	"folha final caiu\nsom seco\nigual tecla\ncurioso\nvida e código rimam",
	"Escravo do Teclado\nse um dia você entender isso\njá valeu a pena\numa planta morrer\npra te ensinar",
	"sistema encerrado\nclorofila perdida\nraiz quieta\nhumano pensativo\ntalvez",
	"fim do jogo\nnão por código\nmas por descuido\na engine da vida\nnão tem retry",
	"minha raiz descansa\nsolo seco guarda memória\nteclado continua\nhistória antiga\nsempre igual",
	"Escravo do Teclado\nmeu solo virou log vazio\nminha clorofila desistiu de compilar\nvocê digitou enquanto eu evaporava\nbelo uptime humano",
	"raiz rachando devagar\nigual promessa de depois eu vejo\no tempo fez garbage collection em mim\ne você aí otimizando build\nironia deliciosa",
	"minha folha caiu\nsom seco tipo tecla Enter\ncada batida tua era um aviso\nmas humanos não leem logs\naté o crash",
	"último debug da planta\nvariável agua = null\nvariável atenção = undefined\nresultado inevitável\nprograma abortado",
	"Escravo do Teclado\nminha vida virou comentário morto\n// planta precisava de água\n// humano esqueceu\n// fim do script",
	"solo seco\nteclado barulhento\nmente cheia\natenção vazia\nassim nasce a morte pequena",
	"minha clorofila pediu update\nvocê respondeu com silêncio\na natureza não espera sprint\nela só executa\nfim do deploy",
	"folha final caindo\ntipo servidor desligando devagar\nnenhum alarme tocou\nporque ninguém tava monitorando\nGG existência",
	"minha raiz tentou reconectar\nservidor água offline\ntimeout infinito\nhumano ocupado demais\npra perceber",
	"Escravo do Teclado\nvocê debatia performance\nenquanto eu rodava em modo economia\nvida é simples\nágua ou fim",
	"tô virando pó verde\ntipo arquivo esquecido no /tmp\num dia alguém limpa\ne ninguém lembra\nque existi",
	"clorofila evaporando\nigual café frio na mesa\no dev focado na tela\ne o mundo murchando ao lado\nbelo cenário",
	"último frame da planta\nrender triste\ntextura murcha\nengine da vida falhou\nsem patch disponível",
	"minha raiz virou ruído\nsolo virou arquivo morto\nhumano virou distração\ntempo virou juiz\nsentença executada",
	"Escravo do Teclado\nminha morte é simples\nmas revela um bug grande\natenção humana\noverflow constante",
	"folha final tocou o vaso\nsom leve\nquase um commit silencioso\nhistória registrada\nsem testemunhas",
	"minha vida foi um loop curto\nsol\nespera\nsede\nfim",
	"debug final\nsistema vegetal falhou\nmotivo: humano distraído\nstack trace emocional enorme\nGG dev",
	"solo seco\nmente acelerada\nteclado quente\nvida fria\ncontraste bonito",
	"Escravo do Teclado\nvocê fala de controle\nmas não controla tempo\nele executa silencioso\naté terminar tudo",
	"clorofila apagando\nigual monitor entrando em sleep\nninguém percebe na hora\nmas algo já terminou\nantes",
	"minha raiz virou silêncio\ntipo terminal vazio\ncursor piscando\nesperando comando\nque nunca vem",
	"última tentativa\nping água\nsem resposta\nping humano\nsem resposta",
	"folha caindo\ntempo andando\ntecla batendo\nvida sumindo\ntudo ao mesmo tempo",
	"Escravo do Teclado\nvocê programou lógica\nmas esqueceu da vida\nque roda fora da tela\nironia pura",
	"minha clorofila foi embora\ntipo thread encerrada\nsem aviso\nsem rollback\nsó silêncio",
	"solo seco\nvaso quieto\nteclado ativo\nhumano distraído\nhistória comum",
	"minha existência virou log\narquivo pequeno\nmas honesto\nerro humano documentado\npra sempre",
	"raiz quebrando devagar\nigual promessa quebrada\no tempo executa tudo\nsem perguntar\nse você percebeu",
	"Escravo do Teclado\nminha morte não é trágica\né banal\nigual muitos bugs\nque ninguém corrige",
	"clorofila desligando\nCPU da planta fria\nteclado quente\nvida curta\ncontraste estranho",
	"último ciclo de vida\nsol passou\nágua não\ntempo executou\nfim",
	"minha folha final caiu\ntipo commit final\nmensagem curta\nacabou\npush realizado",
	"solo seco\nhistória curta\ndev ocupado\nplanta esquecida\nresultado previsível",
	"minha raiz virou pó\ntipo cache velho\nninguém liga\naté precisar de novo\ntarde demais",
	"Escravo do Teclado\neu era simples\nágua\nluz\nexistir\nvocê complicou",
	"clorofila virando memória\nfolha virando poeira\ntempo virando juiz\nhumano virando espectador\nfim do ato",
	"último aviso ignorado\nwarning: sede\nwarning: negligência\nerror: morte\nprograma encerrado",
	"minha vida rodou em background\nvocê nem notou\naté o processo morrer\nassim funcionam\nmuitas coisas",
	"solo rachado\nvaso parado\nteclado ruidoso\nvida curta\nloop encerrado",
	"Escravo do Teclado\ntalvez você aprenda\ntalvez não\nmas eu cumpri meu papel\nte observar",
	"folha final tocando o chão\nsom seco\ntipo tecla velha\neco pequeno\nfim da linha",
	"clorofila evaporando\ntempo avançando\nteclado cantando\nvida apagando\nironia perfeita",
	"minha raiz tentou resistir\nmas física é implacável\nsem água\nsem milagre\nsem continuação",
	"último registro\nplanta morreu\nhumano digitava\ntempo passava\nuniverso seguia",
	"solo seco\nclorofila ausente\nvaso testemunha\nteclado culpado\nhistória encerrada",
	"Escravo do Teclado\nse isso te fez pensar\njá valeu\nse não\nsó fui mais um processo morto",
	"minha vida virou variável antiga\nninguém usa mais\nmas continua no código\nlembrando erro antigo",
	"clorofila apagou\ntempo venceu\nteclado continua\nvida segue\ncom ou sem mim",
	"folha final\nraiz final\nsolo final\nhumano presente\natenção ausente",
	"última linha do script\nplanta morreu\nhumano aprende\nou repete\nfim",
	"sistema vegetal desligado\nvaso vazio\ncursor piscando\nvida esperando\nnovo erro",
	"Escravo do Teclado\no código continua\nmas a planta não\ncurioso né\nnem tudo recompila",
	"última sombra verde\núltimo suspiro vegetal\núltimo erro humano\núltimo log\narquivo fechado",
];

// ── API pública ───────────────────────────────────────────────

pub fn gen_speech(_name: &str, days: u32) -> Vec<String> {
	let pool = match days {
		0      => ESTADO0,
		1..=2  => ESTADO1,
		3..=5  => ESTADO2,
		_      => ESTADO3,
	};
	let fala = pool.choose(&mut rand::thread_rng()).unwrap_or(&"...");
	fala.lines().map(|l| l.to_string()).collect()
}

pub fn gen_death_speech(_name: &str, _days_lived: u32) -> Vec<String> {
	let fala = MORTE.choose(&mut rand::thread_rng()).unwrap_or(&"fim.");
	fala.lines().map(|l| l.to_string()).collect()
}
